In [1]:
import numpy as np

In [2]:
np.array([1,2,4])

array([1, 2, 4])

In [4]:
np.array([[1,3,5],[6,3,5]]) # two dimentional array

array([[1, 3, 5],
       [6, 3, 5]])

In [5]:
np.array([[3,5],[4,6],[3,2]]) # three dimentional array

array([[3, 5],
       [4, 6],
       [3, 2]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
3*np.eye(4)

array([[3., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 3.]])

In [10]:
np.zeros(shape = (3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(shape =(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
np.arange(5,100,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [15]:
np.arange(3,67,4)

array([ 3,  7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59, 63])

In [16]:
np.arange(100,5,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [17]:
np.linspace(0,100,5) # creates sequences of evenly spaced values within a defined interval.

array([  0.,  25.,  50.,  75., 100.])

In [18]:
np.linspace(4,40,4)

array([ 4., 16., 28., 40.])

In [19]:
np.linspace(3,67,4)

array([ 3.        , 24.33333333, 45.66666667, 67.        ])

In [20]:
np.random.rand(2,3) # two dimentional

array([[0.14714348, 0.16085668, 0.71156232],
       [0.7518703 , 0.79320177, 0.68744089]])

In [21]:
np.random.rand(2,3,5) # three dientional

array([[[0.48982311, 0.04927484, 0.17616791, 0.57012843, 0.71188717],
        [0.62329402, 0.65693737, 0.34446255, 0.81694824, 0.16456494],
        [0.3010265 , 0.39017468, 0.36145102, 0.94594527, 0.59612019]],

       [[0.45932729, 0.98069632, 0.76382358, 0.80374171, 0.41604118],
        [0.17547712, 0.35610061, 0.034778  , 0.39300428, 0.3546567 ],
        [0.39184218, 0.19476513, 0.48012078, 0.04456578, 0.95068592]]])

In [22]:
np.random.randn(3,4) # normally dostributed numbers

array([[-2.161022  , -0.70386361, -2.79464169, -1.23946426],
       [-0.17116117,  0.41342001, -0.05435796,  0.58396727],
       [ 0.19699889, -0.06729061, -1.12349325, -0.18235894]])

In [24]:
 np.random.randint(3,67) # generates random int between two points

38

In [25]:
np.random.randint(3,67,5) # generates 5 random int between two points

array([48, 14, 27, 51, 14])

In [26]:
mtr = np.random.rand(3,4)

In [27]:
mtr

array([[0.85802503, 0.50762734, 0.93600921, 0.4058543 ],
       [0.69369404, 0.55830069, 0.860202  , 0.68847289],
       [0.16310276, 0.43295655, 0.84634519, 0.0406654 ]])

In [32]:
mtr.size

12

In [30]:
mtr.shape

(3, 4)

In [33]:
mtr.reshape(2,6)

array([[0.85802503, 0.50762734, 0.93600921, 0.4058543 , 0.69369404,
        0.55830069],
       [0.860202  , 0.68847289, 0.16310276, 0.43295655, 0.84634519,
        0.0406654 ]])